### ISSUE TITLE
Fix link for "A Metric Learning Reality Check"

### ISSUE THREAD

**Issue by KevinMusgrave** [kdhht2334/Survey_of_Deep_Metric_Learning#1]
This is a great resource! I'm one of the authors of "A Metric Learning Reality Check", and I just wanted to point out that the associated link should be either https://github.com/KevinMusgrave/powerful-benchmarker or https://github.com/KevinMusgrave/pytorch-metric-learning. 

Cheers,

Kevin

**Comment by kdhht2334** [comment]
Thanks for your informative advice!

Both repositories you suggested are much helpful for me.
