### ISSUE TITLE
ECCV20 papers

### ISSUE THREAD

**Issue by abcdvzz** [kdhht2334/Survey_of_Deep_Metric_Learning#3]
A unifying mutual information view of metric learning: cross-entropy vs. pairwise losses
The Group Loss for Deep Metric Learning
Unsupervised Deep Metric Learning with Transformed Attention Consistency and Contrastive Clustering Loss
Spherical Feature Transform for Deep Metric Learning
A Simple and Effective Framework for Pairwise Deep Metric Learning
BioMetricNet: deep unconstrained face verification through learning of metrics regularized onto Gaussian distributions
Deep Credible Metric Learning for Unsupervised Domain Adaptation Person Re-identification

**Comment by kdhht2334** [comment]
Thanks for letting me know few papers.

I'll consider about that and add it.
